# Sets up nginx with a Letsencrypt certificate and redirects HTTP/S traffic to a given application port

# Need to update Spacewalk to sync OEL 7 extras if it does not already; this package is present in that repo.
#- name: Install letsencrypt dependency
#  yum:
#    name: https://yum.oracle.com/repo/OracleLinux/OL7/developer_EPEL/x86_64/getPackageSource/python2-zope-interface-4.0.5-0.el7.src.rpm
#    state: present

- name: Install letsencrypt
  yum: 
    name: letsencrypt
    state: latest

- name: Create letsencrypt directory
  file: 
    name: /var/www/letsencrypt
    state: directory

- name: Remove default nginx config
  file: 
    name: /etc/nginx/sites-enabled/default
    state: absent

- name: Install system nginx config
  template:
    src: nginx.conf.j2
    dest: /etc/nginx/nginx.conf

- name: Create sites-enabled folder
  file:
    path: /etc/nginx/sites-enabled
    state: directory

- name: Install nginx site for letsencrypt requests
  template:
    src: nginx-http.j2
    dest: /etc/nginx/sites-enabled/http

- name: Reload nginx to activate letsencrypt site
  systemd: 
    name: nginx
    state: restarted

- name: Create letsencrypt certificate
  shell: letsencrypt certonly -n --webroot -w /var/www/letsencrypt -m {{ letsencrypt_email }} --agree-tos -d {{ nginx_domain_name }}
  args:
    creates: /etc/letsencrypt/live/{{ nginx_domain_name }}

- name: Generate dhparams
  shell: openssl dhparam -out /etc/nginx/dhparams.pem 2048
  args:
    creates: /etc/nginx/dhparams.pem

- name: Install nginx site for specified site
  template:
    src: templates/nginx-le.j2
    dest: /etc/nginx/sites-enabled/le

- name: Reload nginx to activate specified site
  service:
    name: nginx
    state: restarted

- name: Add letsencrypt cronjob for cert renewal
  cron:
    name: letsencrypt_renewal
    special_time: weekly
    job: letsencrypt --renew certonly -n --webroot -w /var/www/letsencrypt -m {{ letsencrypt_email }} --agree-tos -d {{ nginx_domain_name }} && service nginx reload

- name: restart nginx
  systemd:
    name: nginx
    state: restarted
